from db_handlers.db_connect.executequery import execute_insertquery
from db_handlers.db_connect.executequery import execute_selectonequery
from db_handlers.db_connect.executequery import execute_insertandreturnquery
from db_handlers.db_connect.executequery import execute_insertandreturnonequery
from db_handlers.db_connect.executequery import execute_insertandreturnallquery